### ISSUE TITLE
How deno load main.ts

### ISSUE THREAD

**Issue by clinyong** [denolib/guide#3]
Hi, thanks for your hard work. The guide is so great. After reading the `Process Lifecycle`, I have a few questions. I don't know whether it is suitable to post an issue here. If you mind, you can close it directly.

In `src/main.rs`, the `isolate` will first execute `denoMain();`.

```rust
  tokio_util::init(|| {
    isolate
      .execute("denoMain();")
      .unwrap_or_else(print_err_and_exit);
    isolate.event_loop().unwrap_or_else(print_err_and_exit);
  });
```
The `denoMain` is defined in `js/main.ts`. How deno load this file?

**Comment by kevinkassimo** [comment]
@clinyong 
`denoMain();` comes from the snapshot:
[Snapshot creator](https://github.com/denoland/deno/blob/master/libdeno/snapshot_creator.cc)
In `BUILD.gn`, this snapshot creator is [invoked against `bundle/main.js`](https://github.com/denoland/deno/blob/535037b519711d238dc0bfa2c4d2ffb4b17dec53/BUILD.gn#L257-L263), which is a bundle for all the compiled TS files:
```
# Generates $target_gen_dir/snapshot_deno.bin
snapshot("snapshot_deno") {
  source_root = "$target_gen_dir/bundle/main.js"
  deps = [
    ":main_bundle",
  ]
}
```
When creating the new `Isolate` in Rust, the generated `snapshot_deno.bin` is loaded to v8. See functions in [`libdeno/api.cc`](https://github.com/denoland/deno/blob/535037b519711d238dc0bfa2c4d2ffb4b17dec53/libdeno/api.cc#L52-L54) and [`src/isolate_init.rs`](https://github.com/denoland/deno/blob/535037b519711d238dc0bfa2c4d2ffb4b17dec53/src/isolate_init.rs#L14-L45) for details.
Snapshot is essentially a serialization of what is on the V8 heap. Once loaded, V8 would restore to the state when the snapshot is taken: the moment `bundle/main.js` has finished execute.

This is why `denoMain()` exists on V8 heap

**Comment by clinyong** [comment]
@kevinkassimo Thanks so much~
